### ISSUE TITLE
Block list should be applied server-wide to Hachyderm

### ISSUE THREAD

**Issue by cparedes** [hachyderm/hack#13]
The current server-wide block list on hachyderm.io is way too short to be of any use. Personally, I’ve had to kill my account (and likely will never come back to Mastodon) because of swarms of right wing extremists not being filtered out by default using #fediblock as a way to find targets for harassment.

**Comment by dmah42** [comment]
which block list are you referring to?

I ask because I personally blocked one of the domains in your screenshot some time ago.

the list of suspensions is public: https://hachyderm.io/about/more

I think we need to upgrade to 4.0.2 before we can start sharing suspended domains (correct me if I'm wrong) and that is happening soon.

I agree completely that we need to start sharing block lists to keep our community safe.

**Comment by cparedes** [comment]
The block list that’s in this repository that seems to be much longer

**Comment by cparedes** [comment]
And this is less about shared block lists via Mastodon 4.0 and more about… expanding the block list on hachyderm altogether

**Comment by jakesmolka** [comment]
I'm very sorry you had to experience that @cparedes! 

Thanks for reporting it. On my end I never encountered such offensive behavior and I only rarely see problematic content at all. So it is valuable to get the feedback when it happens.
(FYI: I'm not a mod on hachyderm.)

**Comment by dmah42** [comment]
> And this is less about shared block lists via Mastodon 4.0 and more about… expanding the block list on hachyderm altogether

understood. however to expand it fully is a very manually intensive task until we get the API for 4.0.  

i will start working through some of these manually, though.

**Comment by dmah42** [comment]
i have completed a manual pass and our defederation list is quite a bit longer.

when we update to 4.0 we will have more options for sharing blocklists between instances and applying them automatically.

i'm really sorry you had such a bad experience, @cparedes, and i really appreciate you pushing us to do better.

**Comment by Jackenmen** [comment]
It seems that hachyderm.io has been updated to 4.0.3 but its list still differs significantly from this repository. Is it planned to replace hachyderm.io's blocklist with the one in this repository (and continue to keep it synced) and if so, is there any open issue for tracking it (since this one has been closed)?
